---
title: "mixtape_DiD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(tidyverse, broom)

```

### Difference-in-Differences

-   RCTよりもずっと前から使われてきたデザイン

-   因果効果の識別条件(identifying assumptions)に焦点を当てる

#### John Snow's Cholera Hypothesis

-   処置があるグループには与えられ、あるグループにはたまたま与えられない、そういう状況が必要

    -   Natural Experiment:Treatment Assignmentが実質的にランダムになっている状況

-   Snow(1855)は、コレラが空気感染ではなく、水を伝って伝染することをDiDデザインで説明した

-   コレラは当初空気感染であると誤解され、それゆえに隔離などが有効な感染防止に繋がらないことなどが課題となった

-   コレラ菌は下痢や嘔吐を引き起こし、下水道に流れて他人の体へ侵入していった

-   コレラが蔓延していない国から来た貨物船の乗組員は、コレラが発生した地域に降りてから感染した。一方、船に残った乗組員は感染しなかった。

-   スノウが発見したパズル：隣り合う2軒の建物、片方はコレラ感染者が続出したが、もう片方はコレラ感染者が出なかった。これらの違いは、水道の汚染状況から説明された。

-   もしスノウがランダム化できるなら：コインで表が出たら、その人は汚染された水道からのむ。裏なら綺麗な水道からのむ。Treatment=汚染された水道の割り当てがランダムになされていることが条件

-   Lambethの水道は、たまたま水道の汚染より上流から水が汲み上げられるように変化した（T=1）ため、1854年の時点では綺麗な水が使えた。一方、Southwark and Vauxhallの水道はそのまま。そして、両方の水道会社の利用世帯はあらゆる共変量のバランスが取れていた（つまり、自然実験的状況だけでなく、両群には大きな違いがない）→ Conditional Independence Assumptions的にもok?

+------------------------+-------------------------+-------------------------+
| Company Name           | 1849                    | 1854                    |
+========================+=========================+=========================+
| Southwark and Vauxhall | 135                     | 147                     |
+------------------------+-------------------------+-------------------------+
| Lambeth                | 85                      | 19                      |
+------------------------+-------------------------+-------------------------+

: Table 69. Modified Table XII(Snow 1854).

#### なぜ単純に1854年の実験群と対照群で比較してはいけないのか？

Treatment = D(clean water)とする

+------------------------+--------------+------------------+-------+-----------+
| Companies              | Time         | Outcome          | Diff1 | Diff2     |
+========================+==============+==================+=======+===========+
| Lambeth                | Before/After | Y=L/Y=L+T+D      | T+D   |           |
+------------------------+--------------+------------------+-------+-----------+
|                        |              | (LはLambethのFE) |       | D(=T+D-T) |
|                        |              |                  |       |           |
|                        |              | (SVは後者のFE)   |       |           |
+------------------------+--------------+------------------+-------+-----------+
| Southwark and Vauxhall | Before/After | Y=SV/Y=SV+T      | T     |           |
+------------------------+--------------+------------------+-------+-----------+

もし普通に差を計算したら、$Y_{LA} - Y_{SVA} = D + (L - SV)$となり、第1項はATE、第2項はselection biasとなってしまう。ランダム化されていないので、selection biasはゼロにならない。

また、同じunitのbefore/afterで差を計算すると、$Y_{LA} - Y_{LB} = T + D$(Diff1)となり、unitで時間を通じて変化するTが残ってしまい、Dのみとならないのが問題

Diff1はBefore/Afterの差を取るので、unit-specific FEを消すことができる。また、Diff2は時間を通じた変化のTを消すことで、Dの不偏推定量を得ることができる。ゆえに、Diff2 = Diff1_T - Diff1_Cで"Difference-in-Differences(差の差推定)"ということ。

#### Key assumption for DD design

"There is no time-variant company specific unobservables"

→ "*T is the same for all units*" : **Parallel Trends Assumption**

#### The simple 2×2 DD

一番シンプルなDDは、Goodman-Bacon(2019)曰く2×2DD

$$
\hat{\delta}_{kU}^{2×2} = \Bigl(\bar{y}^{post(k)}_{k} - \bar{y}^{pre(k)}_{k}\Bigr) - \Bigl(\bar{y}^{post(k)}_{U} - \bar{y}^{pre(k)}_{U}\Bigr)
$$

$\hat{\delta}_{kU}^{2×2}$はgroup kにとってのestimated ATTである。

$$
\begin{align}
\hat{\delta}_{kU}^{2×2} &= \Bigl(E[Y_k|Post] - E[Y_k|Pre] \Bigr) - \Bigl(E[Y_U|Post] - E[Y_U|Pre]\Bigr)\\
&= \Bigl(E[D_kY^1_k + (1 - D_k)Y^0_k|Post] - E[D_kY^1_k + (1 - D_k)Y^0_k|Pre] \Bigr)
 - \Bigl(E[D_UY^1_U + (1 - D_U)Y^0_U|Post] - E[D_UY^1_U + (1 - D_U)Y^0_U|Pre] \Bigr)\\
 & = \Bigl(E[Y^1_k|Post] - E[Y^0_k|Pre] \Bigr) - \Bigl(E[Y^0_U|Post] - E[Y^0_U|Pre] \Bigr) 
 + E[Y^0_k|Post] - E[Y^0_k|Post]\\
 &= E[Y^1_k|Post] - E[Y^0_k|Post] + \Bigl(E[Y^0_k|Post] - E[Y^0_k|Pre] \Bigr) - \Bigl(E[Y^0_U|Post] - E[Y^0_U|Pre]\Bigr)\\
 &= \text{ATT for group k} + \text{Non-parallel trends bias in 2×2 case}
\end{align}
$$

ただし、$\text{the switching equation: }Y_i = D_iY^1_i + (1 -D_i)Y^0_i \text{ for k, U}$を用いた。

また、当たり前だが、処置群において、$D_i = 1 \text{ iff t = Post & i = k}$であることに注意。 ここで4行目に注目すると、$t = Post$なのに$Y^0_k$が出てきている。

つまり、$ATT$はcounterfactualであり、第2項はparallel trends assumptionそのものである。
